export interface GetSlackConfigResponse {
    bot_token: string,
    app_token: string,
    app_id: string, 
    client_id: string,
    client_secret: string,
    signing_secret: string,
    verification_token: string,
}

export interface GetSlackCustomerResponse {
    id: number,
    created_at: string,
    updated_at: string,
    uuid: string,
    email: string,
    nickname: string,
    avatar: string,
    description: string,
    is_enable: boolean,
    first_name: string,
    last_name: string,
    real_name: string,
    real_name_normalized: string,
    display_name: string,
    display_name_normalized: string,
    skype: string,
    phone: string,
    image_24: string,
    image_32: string,
    image_48: string,
    image_72: string,
    image_192: string,
    image_512: string,
    image_original: string,
    title: string,
    status_expiration: number,
    team: string,
}