# Copyright © 2023 OpenIMSDK open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

app:
  version: 1.0-dev
  debug: true
  log_file: logs/

server:
  ip: 127.0.0.1
  port: 10010

jwt:
  secret: openkf
  issuer: openkf
  expire_days: 1

mysql:
  ip: 127.0.0.1
  port: 3307
  username: root
  password: 123123
  database: openkf

redis:
  ip: 127.0.0.1
  port: 6380
  password: openkf
  database: 0

minio:
  ip: 127.0.0.1
  port: 9123
  access_key_id: test123123
  secret_access_key: test123123
  bucket: openkf
  app_bucket: openkf
  location: us-east-1