#!/usr/bin/env bash

# Copyright © 2023 OpenIMSDK & Xinwei Xiong(cubxxw). All rights reserved.
#
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

#
# ==============================================================================
#
# Store this file as .git/hooks/commit-msg in your repository in order to
# enforce checking for proper commit message format before actual commits.
# You may need to make the script executable by 'chmod +x .git/hooks/commit-msg'.

# commit-msg use go-gitlint tool, install go-gitlint via `go get github.com/llorllale/go-gitlint/cmd/go-gitlint`
# go-gitlint --msg-file="$1"

# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

YELLOW="\e[93m"
GREEN="\e[32m"
RED="\e[31m"
ENDCOLOR="\e[0m"

printMessage() {
   printf "${YELLOW}OpenIMSDK : $1${ENDCOLOR}\n"
}

printSuccess() {
   printf "${GREEN}OpenIMSDK : $1${ENDCOLOR}\n"
}

printError() {
   printf "${RED}OpenIMSDK : $1${ENDCOLOR}\n"
}

printMessage "Running the OpenIMSDK commit-msg hook."

# This example catches duplicate Signed-off-by lines.

test "" = "$(grep '^Signed-off-by: ' "$1" |
	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
	echo >&2 Duplicate Signed-off-by lines.
	exit 1
}

# TODO: go-gitlint dir set
GITLINT_DIR="./_output/tools/go-gitlint"

$GITLINT_DIR \
    --msg-file=$1 \
    --subject-regex="^(build|chore|ci|docs|feat|feature|fix|perf|refactor|revert|style|test)(.*)?:\s?.*" \
    --subject-maxlen=150 \
    --subject-minlen=10 \
    --body-regex=".*" \
    --max-parents=1

if [ $? -ne 0 ]
then
    if ! command -v $GITLINT_DIR &>/dev/null; then
        printError "$GITLINT_DIR not found. Please run 'make tools' OR 'make tools.verify.go-gitlint' make verto install it."
    fi
    printError "Please fix your commit message to match OpenIMSDK coding standards"
    printError "https://gist.github.com/cubxxw/126b72104ac0b0ca484c9db09c3e5694#file-githook-md"
    exit 1
fi