# Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file.

name: OpenKF golangci-lint
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            # Require: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
            version: v1.53

            # Optional: working directory, useful for monorepos
            working-directory: server

            # Optional: golangci-lint command line arguments.
            # 
            # Note: by default the `.golangci.yml` file should be at the root of the repository.
            # The location of the configuration file can be changed by using `--config=`
            # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0

            # Optional: show only new issues if it's a pull request. The default value is `false`.
            only-new-issues: true

            # Optional:The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
            install-mode: "goinstall"